# import numpy as np                        //creating numpy 1d array and checking its type
# arr1 = np.array([1,2,3,4,5])
# print(arr1)
# print(type(arr1))
# import numpy as np                          #creating numpy 2d array and checking its type
# arr = np.array([[1,2,3],[4,5,6]])
# print(arr)
# print(type(arr))
import numpy as np
# arr = np.zeros((2,3))
# print(arr)
# arr = np.ones((3,3))
# print(arr)
# arr = np.identity(5)
# print(arr)
# arr = np.arange(10)
# print(arr)
# arr = np.arange(5,16)
# print(arr)
arr7 = np.arange(5,16,2)
print(arr7)
arr8 = np.linspace(10,20,10)
print(arr8)
arr8 = arr7.copy()
print(arr8) 